//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.12 at 10:10:20 AM MST 
//


package xml.taxonomy.beans.key;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Statement_QNAME = new QName("", "statement");
    private final static QName _Discussion_QNAME = new QName("", "discussion");
    private final static QName _Source_QNAME = new QName("", "source");
    private final static QName _KeyAuthor_QNAME = new QName("", "key_author");
    private final static QName _NextStatementId_QNAME = new QName("", "next_statement_id");
    private final static QName _OtherInfoOnMeta_QNAME = new QName("", "other_info_on_meta");
    private final static QName _KeyHead_QNAME = new QName("", "key_head");
    private final static QName _Key_QNAME = new QName("", "key");
    private final static QName _KeyHeading_QNAME = new QName("", "key_heading");
    private final static QName _StatementId_QNAME = new QName("", "statement_id");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KeyStatement }
     * 
     */
    public KeyStatement createKeyStatement() {
        return new KeyStatement();
    }

    /**
     * Create an instance of {@link Determination }
     * 
     */
    public Determination createDetermination() {
        return new Determination();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link ProcessedBy }
     * 
     */
    public ProcessedBy createProcessedBy() {
        return new ProcessedBy();
    }

    /**
     * Create an instance of {@link Charaparser }
     * 
     */
    public Charaparser createCharaparser() {
        return new Charaparser();
    }

    /**
     * Create an instance of {@link Processor }
     * 
     */
    public Processor createProcessor() {
        return new Processor();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "statement")
    public JAXBElement<String> createStatement(String value) {
        return new JAXBElement<String>(_Statement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "discussion")
    public JAXBElement<String> createDiscussion(String value) {
        return new JAXBElement<String>(_Discussion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "key_author")
    public JAXBElement<String> createKeyAuthor(String value) {
        return new JAXBElement<String>(_KeyAuthor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "next_statement_id")
    public JAXBElement<String> createNextStatementId(String value) {
        return new JAXBElement<String>(_NextStatementId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "other_info_on_meta")
    public JAXBElement<String> createOtherInfoOnMeta(String value) {
        return new JAXBElement<String>(_OtherInfoOnMeta_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "key_head")
    public JAXBElement<String> createKeyHead(String value) {
        return new JAXBElement<String>(_KeyHead_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Key }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "key")
    public JAXBElement<Key> createKey(Key value) {
        return new JAXBElement<Key>(_Key_QNAME, Key.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "key_heading")
    public JAXBElement<String> createKeyHeading(String value) {
        return new JAXBElement<String>(_KeyHeading_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "statement_id")
    public JAXBElement<String> createStatementId(String value) {
        return new JAXBElement<String>(_StatementId_QNAME, String.class, null, value);
    }

}
