//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.22 at 03:49:58 PM MST 
//


package xml.taxonomy.beans.treatment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for taxon_identification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="taxon_identification">
 *   &lt;complexContent>
 *     &lt;extension base="{}taxon_identification">
 *       &lt;redefine>
 *         &lt;complexType name="taxon_identification">
 *           &lt;complexContent>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;choice maxOccurs="unbounded">
 *                 &lt;element ref="{}order_name" minOccurs="0"/>
 *                 &lt;element ref="{}order_authority" minOccurs="0"/>
 *                 &lt;element ref="{}suborder_name" minOccurs="0"/>
 *                 &lt;element ref="{}suborder_authority" minOccurs="0"/>
 *                 &lt;element ref="{}superfamily_name" minOccurs="0"/>
 *                 &lt;element ref="{}superfamily_authority" minOccurs="0"/>
 *                 &lt;element ref="{}family_name" minOccurs="0"/>
 *                 &lt;element ref="{}family_authority" minOccurs="0"/>
 *                 &lt;element ref="{}subfamily_name" minOccurs="0"/>
 *                 &lt;element ref="{}subfamily_authority" minOccurs="0"/>
 *                 &lt;element ref="{}tribe_name" minOccurs="0"/>
 *                 &lt;element ref="{}tribe_authority" minOccurs="0"/>
 *                 &lt;element ref="{}subtribe_name" minOccurs="0"/>
 *                 &lt;element ref="{}subtribe_authority" minOccurs="0"/>
 *                 &lt;element ref="{}genus_name" minOccurs="0"/>
 *                 &lt;element ref="{}genus_group_name" minOccurs="0"/>
 *                 &lt;element ref="{}genus_authority" minOccurs="0"/>
 *                 &lt;element ref="{}subgenus_name" minOccurs="0"/>
 *                 &lt;element ref="{}subgenus_authority" minOccurs="0"/>
 *                 &lt;element ref="{}section_name" minOccurs="0"/>
 *                 &lt;element ref="{}section_authority" minOccurs="0"/>
 *                 &lt;element ref="{}subsection_name" minOccurs="0"/>
 *                 &lt;element ref="{}subsection_authority" minOccurs="0"/>
 *                 &lt;element ref="{}series_name" minOccurs="0"/>
 *                 &lt;element ref="{}series_authority" minOccurs="0"/>
 *                 &lt;element ref="{}species_name" minOccurs="0"/>
 *                 &lt;element ref="{}species_group_name" minOccurs="0"/>
 *                 &lt;element ref="{}species_authority" minOccurs="0"/>
 *                 &lt;element ref="{}subspecies_name" minOccurs="0"/>
 *                 &lt;element ref="{}subspecies_authority" minOccurs="0"/>
 *                 &lt;element ref="{}variety_name" minOccurs="0"/>
 *                 &lt;element ref="{}variety_authority" minOccurs="0"/>
 *                 &lt;element ref="{}unranked_epithet_name" minOccurs="0"/>
 *                 &lt;element ref="{}unranked_epithet_authority" minOccurs="0"/>
 *                 &lt;element ref="{}other_info_on_name" minOccurs="0"/>
 *                 &lt;element ref="{}place_of_publication" minOccurs="0"/>
 *               &lt;/choice>
 *               &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *             &lt;/restriction>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}taxon_hierarchy" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "taxon_identification", propOrder = {
    "taxonHierarchy"
})
public class TaxonIdentification
    extends OriginalTaxonIdentification
{

    @XmlElement(name = "taxon_hierarchy")
    protected List<String> taxonHierarchy;

    /**
     * Gets the value of the taxonHierarchy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxonHierarchy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxonHierarchy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTaxonHierarchy() {
        if (taxonHierarchy == null) {
            taxonHierarchy = new ArrayList<String>();
        }
        return this.taxonHierarchy;
    }

}
