/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paragraph.bean;

/**
 *
 * @author iychoi
 */
public enum ParagraphType {
    PARAGRAPH_UNKNOWN,
    PARAGRAPH_IGNORE,
    
    PARAGRAPH_TAXONOMY_NAME,
    PARAGRAPH_TAXONOMY_OTHERINFO,
    PARAGRAPH_TAXONOMY_SYNONYM,
    PARAGRAPH_TAXONOMY_TYPESPECIES,
    PARAGRAPH_TAXONOMY_DIAGNOSIS,
    PARAGRAPH_TAXONOMY_DEFINITION,
    PARAGRAPH_TAXONOMY_DESCRIPTION,
    PARAGRAPH_TAXONOMY_KEY_TO_FAMILY,
    PARAGRAPH_TAXONOMY_DISTRIBUTION,
    PARAGRAPH_TAXONOMY_DISCUSSION,
    PARAGRAPH_TAXONOMY_OTHERS_TITLE,
    PARAGRAPH_TAXONOMY_OTHERS_CONTENT,
    PARAGRAPH_TAXONOMY_DISCUSSION_TITLE,
    PARAGRAPH_TAXONOMY_DISCUSSION_CONTENT,
    PARAGRAPH_TAXONOMY_ACKNOWLEDGEMENT,
}
