/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paragraph.bean;

/**
 *
 * @author iychoi
 */
public enum ParagraphType {
    PARAGRAPH_UNKNOWN,
    PARAGRAPH_IGNORE,
    
    PARAGRAPH_ABSTRACT,
    PARAGRAPH_ABSTRACT_BODY,
    PARAGRAPH_TITLE,
    PARAGRAPH_AUTHOR,
    PARAGRAPH_AUTHOR_DETAILS,
    PARAGRAPH_KEYWORDS,
    
    PARAGRAPH_INTRODUCTION,
    PARAGRAPH_INTRODUCTION_BODY,
    PARAGRAPH_MATERIALS_METHOD,
    PARAGRAPH_MATERIALS_METHOD_BODY,
    PARAGRAPH_DISTRIBUTION,
    PARAGRAPH_DISTRIBUTION_BODY,
    PARAGRAPH_DISTRIBUTION_WITH_BODY,
    PARAGRAPH_KEY,
    PARAGRAPH_KEY_BODY,
    PARAGRAPH_REMARKS,
    PARAGRAPH_REMARKS_BODY,
    PARAGRAPH_REMARKS_WITH_BODY,
    PARAGRAPH_ACKNOWLEDGEMENT,
    PARAGRAPH_ACKNOWLEDGEMENT_BODY,
    PARAGRAPH_TAXONNAME,
    PARAGRAPH_OTHERINFO,
    PARAGRAPH_SYNONYM,
    PARAGRAPH_DIAGNOSIS,
    PARAGRAPH_DIAGNOSIS_BODY,
    PARAGRAPH_DEFINITION,
    PARAGRAPH_DEFINITION_BODY,
    PARAGRAPH_DESCRIPTION,
    PARAGRAPH_DESCRIPTION_BODY,
    PARAGRAPH_TYPESPECIES,
    PARAGRAPH_TYPESPECIES_BODY,
    PARAGRAPH_DISCUSSION_BODY,
    PARAGRAPH_DISCUSSION_SUBTITLE,
    PARAGRAPH_DISCUSSION_SUBBODY,
    PARAGRAPH_SUBTITLE,
    PARAGRAPH_SUBBODY,
}
