/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paragraph.bean;

/**
 *
 * @author iychoi
 */
public enum ParagraphType {
    PARAGRAPH_UNKNOWN,
    PARAGRAPH_IGNORE,
    
    PARAGRAPH_TITLE,
    PARAGRAPH_KEYWORDS,
    
    PARAGRAPH_INTRODUCTION,
    PARAGRAPH_INTRODUCTION_BODY,
    PARAGRAPH_MATERIAL,
    PARAGRAPH_MATERIAL_BODY,
    PARAGRAPH_MATERIAL_WITH_BODY,
    PARAGRAPH_ARTICULATION,
    PARAGRAPH_ARTICULATION_BODY,
    PARAGRAPH_ARTICULATION_WITH_BODY,
    PARAGRAPH_HABITAT,
    PARAGRAPH_HABITAT_BODY,
    PARAGRAPH_HABITAT_WITH_BODY,
    PARAGRAPH_ELEVATION,
    PARAGRAPH_ELEVATION_BODY,
    PARAGRAPH_ELEVATION_WITH_BODY,
    PARAGRAPH_ECOLOGY,
    PARAGRAPH_ECOLOGY_BODY,
    PARAGRAPH_ECOLOGY_WITH_BODY,
    PARAGRAPH_DISTRIBUTION,
    PARAGRAPH_DISTRIBUTION_BODY,
    PARAGRAPH_DISTRIBUTION_WITH_BODY,
    PARAGRAPH_TYPE,
    PARAGRAPH_TYPE_BODY,
    PARAGRAPH_TYPE_WITH_BODY,
    PARAGRAPH_KEY,
    PARAGRAPH_KEY_BODY,
    PARAGRAPH_KEY_DISCUSSION,
    PARAGRAPH_REMARKS,
    PARAGRAPH_REMARKS_BODY,
    PARAGRAPH_REMARKS_WITH_BODY,
    PARAGRAPH_ACKNOWLEDGEMENT,
    PARAGRAPH_ACKNOWLEDGEMENT_BODY,
    PARAGRAPH_TAXONNAME,
    PARAGRAPH_OTHERINFO,
    PARAGRAPH_SYNONYM,
    PARAGRAPH_DESCRIPTION,
    PARAGRAPH_DESCRIPTION_BODY,
    PARAGRAPH_DESCRIPTION_WITH_BODY,
    PARAGRAPH_DISCUSSION,
    PARAGRAPH_DISCUSSION_BODY,
    PARAGRAPH_DISCUSSION_WITH_BODY,
    PARAGRAPH_DISCUSSION_NON_TITLED_BODY,
}
